let attire = {
    headGear: "",
    smogMask: "",
    shirt: "",
    jacket: "",
    gloves: "",
    pants: "",
    socks: "",
    shoes: "",
    overshoes: "",
    armWarmers: "",
    legWarmers: "",
    rainJacket: "",
    glasses: "",
}